import { RECIPE_ASSISTANT_URL } from "../constants/urls";

const RECIPE_ASSISTANT_TASK2_URL = `${RECIPE_ASSISTANT_URL}/task2`;

export const RECIPE_ASSISTANT_TASK2_INSTRUCTIONS_URL = `${RECIPE_ASSISTANT_TASK2_URL}/instructions`;
export const RECIPE_ASSISTANT_TASK2_INGREDIENTS_URL = `${RECIPE_ASSISTANT_TASK2_URL}/ingredients`;
