import { RECIPE_ASSISTANT_URL } from "../constants/urls";

const RECIPE_ASSISTANT_TASK3_URL = `${RECIPE_ASSISTANT_URL}/task3`;

export const RECIPE_ASSISTANT_TASK3_INSTRUCTIONS_URL = `${RECIPE_ASSISTANT_TASK3_URL}/instructions`;
export const RECIPE_ASSISTANT_TASK3_INGREDIENTS_URL = `${RECIPE_ASSISTANT_TASK3_URL}/ingredients`;
export const RECIPE_ASSISTANT_TASK3_RECOMMEND_URL = `${RECIPE_ASSISTANT_TASK3_URL}/recommend`;
